### ISSUE TITLE
Error when saving any file: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by awaer** [sindresorhus/broccoli-autoprefixer#13] opened 2015-11-23 14:52 UTC
Ember: v2.1.0
Ember CLI: v1.13.8

(Cross-posted from https://github.com/kimroen/ember-cli-autoprefixer/issues/25)

A build error is triggered when any files are saved after starting `ember serve`. This issue appears to be connected to the release of broccoli-autoprefixer v4.1.0. 

The error is prevented if I force broccoli-autoprefixer v4.0.0, though this seems to have the unfortunate side effect of breaking livereload of styles. The only real "fix" during development is to temporarily disable autoprefixer entirely using `autoprefixer: { enabled: false ... }`. 

I've been unsuccessful in tracking down what exactly this issue is, but I'd be happy to provide more information about my build if necessary. 

```javascript
ENOENT, no such file or directory '/Projects/Thing/ember/tmp/autoprefixer_filter-output_path-NncgYwdM.tmp/assets/old-ie.js'
Error: ENOENT, no such file or directory '/Projects/Thing/ember/tmp/autoprefixer_filter-output_path-NncgYwdM.tmp/assets/old-ie.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at copyDereferenceSync (/Projects/Thing/ember/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:13:21)
    at copyDereferenceSync (/Projects/Thing/ember/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:31:7)
    at Function.copyDereferenceSync (/Projects/Thing/ember/node_modules/ember-cli/node_modules/ember-cli-copy-dereference/index.js:31:7)
    at /Projects/Thing/ember/node_modules/ember-cli/lib/models/builder.js:103:19
    at lib$rsvp$$internal$$initializePromise (/Projects/Thing/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:541:9)
    at PromiseExt.lib$rsvp$promise$$Promise [as _superConstructor] (/Projects/Thing/ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:757:9)
    at new PromiseExt (/Projects/Thing/ember/node_modules/ember-cli/lib/ext/promise.js:32:8)
    at Class.module.exports.Task.extend.copyToOutputPath (/Projects/Thing/ember/node_modules/ember-cli/lib/models/builder.js:98:12)
```

**Comment by stefanpenner** [comment] 2015-11-23 17:34
@awaer can you provide an example app demonstrating the issue, I will gladly debug that.

**Comment by awaer** [comment] 2015-11-23 19:56
@stefanpenner I managed to recreate it in a basic app https://github.com/awaer/thing The problem began once I added the vendor-top.js asset.

**Comment by stefanpenner** [comment] 2015-11-23 19:58
@awaer thanks, installing it now. Will investigate after lunch

**Comment by stefanpenner** [comment] 2015-11-23 21:22
So I was able to reproduce the issue. It is the intersection of several things.

1. legacy rebuild (using unstable dir) vs new patch based plugins
2. OS symlink issues forcing us to collapse symlinks

Short term fix (and my advice) is to upgrade broccoli-cancat to broccoli-sourcemap-concat.

I am going to investigate the interaction between the various plugins and see if there is a reasonable solution during the transitional period.

**Comment by stefanpenner** [comment] 2015-11-23 21:56
After some further investigation, the root cause is needless instability [here](https://github.com/joliss/node-quick-temp/blob/master/index.js#L10) i'll be submitting a PR shortly

**Comment by stefanpenner** [comment] 2015-11-23 22:03
patch: https://github.com/joliss/node-quick-temp/pull/9

**Comment by awaer** [comment] 2015-11-23 22:06
Great, thanks @stefanpenner!

**Comment by stefanpenner** [comment] 2015-11-23 22:23
Im going to close this issue. It isn't an issue with this library, rather a (somewhat confusing interopt between other libs), that made it appear that the issue was here.

For those that might run into this specific configuration, I would recommend using broccoli-sourcemap-concat (which I actively maintain, and also works without sourcemaps).

Going for broccoli 1.0 wont support these legacy plugins any longer, so its worth upgrading to something supported.

The specific issue that was reported hear has a appropriate PR's open to address.

**Comment by stefanpenner** [comment] 2015-11-23 22:24
Anyone else running into this, please provide a reduced example that demonstrates the issue, and i can gladly debug the issue.

**Closed by stefanpenner** 2015-11-23 22:23 UTC

**Comment by kimroen** [comment] 2015-11-23 22:27
Thanks for the herculean efforts, Stefan!
